### PR TITLE
compatible with old php version

### PR DESCRIPTION
**Pull request by huyanping**

### CODE REVIEW

**Comment by gabrielbull** [comment]
Thansk!

**Comment by huyanping** [comment]
Can you release a new package version? So I can replace my own package on packagist website.

**Comment by gabrielbull** [comment]
Done

**Comment by huyanping** [comment]
I am sorry that I had modify the composer.json file because I want to submit a package on packagist.So I can keep going to write my program. When I was pushing it, I forget that and I pushed it to you.The package name has been modified to 'Jenner/config'. 

Sorry again.

**Comment by gabrielbull** [comment]
Ok, I fixed it. You can use the repositories config in composer.json to change a package's location without having to submit a new project to packagist:

```json
{
  "repositories": [
    {
      "type": "vcs",
      "url": "git@github.com:sinergi/config.git"
    }
  ],
  "require": {
    "sinergi/config": "dev-master"
  }
}
```

**Comment by huyanping** [comment]
Thank you and your package. Sorry for my bad English. :)

**Pull request merged**
